/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.armyenjoyers.dg

import com.armyenjoyers.dg.documents.OutpatientCard
import com.armyenjoyers.dg.models.Patient
import java.io.File
import kotlin.test.Test

class DocGeneratorTest {
    @Test
    fun anyDataDocumentTest() {
        val document = OutpatientCard(Patient(firstName = "Sasha", lastName = "Shikutskaya"))
        val docStream = DocGenerator.generate(document)
        docStream.writeTo(File("${document.getSimpleName()}.docx").outputStream())
    }
}
