/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.armyenjoyers.dg

import com.armyenjoyers.dg.schemas.anyData
import java.io.File
import kotlin.test.Test

class DocGeneratorTest {
    @Test fun anyDataDocumentTest() {
        val anyData = anyData("name", "21.12.2012")
        val docStream = DocGenerator.generate(anyData)
        docStream.writeTo(File("anyDataDocument.docx").outputStream())
    }
}
