/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.armyenjoyers.dg

class Library {
    fun someLibraryMethod(): Boolean {
        println("SomeLibraryMethod")
        return true
    }

}
fun main(){
    println("main")
}